### ISSUE TITLE
Failed to load payload for github-repo: timedout

### ISSUE THREAD

**Issue by epipav** [revanite-io/pvtr-github-repo#77]
**Description**

Running the plugin against big monorepos with many dependency files results in timeout from one of the GraphQl queries . The the [dependencyGraphManifests](https://github.com/revanite-io/pvtr-github-repo/blob/eff5bcb63b70227b76ca41a54d834164eafebea9/data/graphql-data.go#L92) part in [GraphqlRepoData](https://github.com/revanite-io/pvtr-github-repo/blob/eff5bcb63b70227b76ca41a54d834164eafebea9/data/graphql-data.go#L13-L14) causes the whole query to time out

**Configuration**
```
loglevel: trace
write-directory: evaluation_results
write: true
output: json
services:
  crowd.dev:
    plugin: github-repo

    policy:
      catalogs:
        - OSPS_B
      applicability:
        - Maturity Level 1

    vars:
      owner: CrowdDotDev
      repo: crowd.dev
      token: <redacted>
```

**Output**
```
./privateer run
2025/04/29 15:24:50 vars: map[]
2025-04-29T15:24:56.493+0200 [ERROR] tests failed in plugin crowd.dev: Failed to load payload for github-repo: timedout
```

**Expected Behavior**
The plugin should be creating crowd.dev.json under `evaluation_results/crowd.dev`

**Actual Behavior**
Log file [crowd.dev.log](https://github.com/user-attachments/files/19959985/crowd.dev.log) is created, but json (`crowd.dev.json`) is missing
